#!/usr/bin/env ruby

#  Copyright (c) 2016, Puzzle ITC GmbH. This file is part of
#  2Redmine and licensed under the Affero General Public License version 3 or later.
#  See the COPYING file at the top-level directory or at
#  https://github.com/puzzle/2Redmine.


require 'date'
require 'json'
require 'restclient'
require './lib/redmine_issue.rb'
require './lib/exporter.rb'
require './lib/option_handler.rb'
require './lib/importers/importer.rb'
require './lib/importers/bugzilla_importer.rb'


require_relative 'lib/to_redmine'

ToRedmine.execute
