#!/usr/bin/env ruby

#  Copyright (c) 2016, Puzzle ITC GmbH. This file is part of
#  2Redmine and licensed under the Affero General Public License version 3 or later.
#  See the COPYING file at the top-level directory or at
#  https://github.com/puzzle/2Redmine.


require 'date'
require 'json'
require 'restclient'
require 'active_support/inflector'
require './lib/redmine_issue.rb'
require './lib/exporter.rb'
require './lib/option_handler.rb'
require './lib/importers/importer.rb'
require './lib/importers/bugzilla_importer.rb'
include OptionHandler

  def self.execute
    raise 'Ruby Version has to be equal or greater than 1.9.3' if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('1.9.3')
    options = OptionHandler.parse
    redmine_issues = Importer.redmine_issues(options)
    e = Exporter.new(redmine_issues, options[:url], options[:apikey])
    e.export
    puts "#{redmine_issues.count} issues exported to redmine successfully!"
  end

execute
